jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArrayNumeralsandOtherSymbol$'

server:
  port: 8081
  error:
    path: /error
# letting the servlet handle the exception
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format-sql: true
        ddl-auto: update
    show-sql: true
    open-in-view: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false